version: '3.3'

services:
  db:
    image: mysql:5.7
    container_name: mysqldb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
